version: '3.1'
services:
  flask:
    image: flask-nextbike
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - "./app:/app"
    networks:
      - examplenet
    container_name: nextbike
    ports:
      - "5000:5000"

networks:
  examplenet:
    name: examplenet
    external: true